### ISSUE TITLE
4. How are the arm disk images generated?

### ISSUE THREAD

**Issue by efzulian** [cirosantilli2/gem5-issues#21]
Hi Ciro, thanks for your posts, they are helpful.
I found this recently:
https://github.com/metempsy/gem5_arm_fullsystem_files_generator.
Regards,
Éder

**Comment by cirosantilli2** [comment]
Thanks Eder, I was not watching my own repo for some reason!

Hmmm, do you understand what is the advantage of that repo over the images on gem5.org? Since they appear to be just downloading and modifying it: https://github.com/metempsy/gem5_arm_fullsystem_files_generator/blob/12235b08777171ee955c9887444b6c81f5e46652/Dockerfile#L49

Here is an alternative setup the builds everything from source with Buildroot: https://github.com/cirosantilli/linux-kernel-module-cheat/tree/83b36867cf06ffdca3ce04296a8568d4f37ea13b#gem5-getting-started

**Comment by efzulian** [comment]
Hi Ciro, my guess is that those images in gem5.org were generated with the docker based gem5_arm_fullsystem_files_generator. Someone could use that to download and install all the dependencies, clone all the repos, get some hints on how to build things and what goes in a new image, add new binaries to the image, etc. Indeed it does not create a rootfs from scratch, does not populate /dev, etc. It just modifies an old version.
Sorry, I was not aware of your Buildroot based setup. I'll take a look on it. Thanks!
You are way ahead on this subject. Closing this issue.
